services:
  saltbox-filebrowser:
    build:
      context: ${FILEBROWSER_COMPOSE_DIR}
      dockerfile: docker/Dockerfile

  saltbox-filebrowser-proxy:
    build:
      context: ${FILEBROWSER_COMPOSE_DIR}
      dockerfile: docker/proxy/Dockerfile
