x-default-service: &default
  restart: "on-failure"
  stop_grace_period: ${STOP_GRACE_PERIOD}

services:
  saltbox-filebrowser:
    <<: *default
    image: "${IMAGE_REGISTRY}/gtstef/filebrowser:${FILEBROWSER_IMAGE_TAG}"
    build:
      context: ${FILEBROWSER_COMPOSE_DIR}
      dockerfile: docker/Dockerfile
    user: "0"
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      MIGRATION_SOURCE_ENABLED: '${FILEBROWSER_MIGRATOR_SOURCE_ENABLED:-false}'
    volumes:
      - "filebrowser_db:/home/filebrowser"
      - "${SALT_MASTER_STORAGE_PATH}:/srv/salt_custom/"
      - "${SSHFS_STORAGE_PATH}:/srv/sshfs"
      - "${SSHFS_MIGRATION_PATH}:/srv/migrator"
      - "salt_repos:/srv/saltbox_salt"

  saltbox-filebrowser-adapter:
    <<: *default
    image: "${IMAGE_REGISTRY}/saltbox-filebrowser-adapter:${FILEBROWSER_ADAPTER_IMAGE_TAG}"
    environment:
      ADAPTER_FILEBROWSER_HOST: "${FILEBROWSER_HOST}"
      ADAPTER_FILEBROWSER_PORT: "${FILEBROWSER_PORT:-80}"
      ADAPTER_FILEBROWSER_BASE_ROUTE: "${FILEBROWSER_BASE_ROUTE}"
      ADAPTER_SERVICE_NAME: "${FILEBROWSER_SERVICE_NAME}"
      ADAPTER_SERVICE_TITLE: "${FILEBROWSER_SERVICE_TITLE}"
      ADAPTER_SERVICE_DESCRIPTION: "${FILEBROWSER_SERVICE_DESCRIPTION}"
      ADAPTER_SERVICE_VENDOR: "${FILEBROWSER_SERVICE_VENDOR}"
      ADAPTER_SERVER_OUTER_SOCKET: "${WEB_SERVER_OUTER_SOCKET}"
      ADAPTER_SERVER_SCHEME: "https"
      ADAPTER_INSTANCE_ID: "${FILEBROWSER_INSTANCE_ID}"
      ADAPTER_DISCOVERY_URL: "http://saltbox-gateway:${GATEWAY_HTTP_PORT}/api/discovery"
    depends_on:
      saltbox-core-init:
        condition: service_completed_successfully
        restart: false
      saltbox-gateway:
        condition: service_started
        restart: false
      saltbox-filebrowser:
        condition: service_started
        restart: false

  saltbox-filesystem-frontend:
    <<: *default
    image: "${IMAGE_REGISTRY}/saltbox-filebrowser-frontend:${FRONTEND_IMAGE_TAG}"
    expose:
      - ${FRONTEND_HTTP_PORT}

volumes:
  filebrowser_db:
    external: false
